### PR TITLE
Create new pilot-things template

### PR DESCRIPTION
**Pull request by Youngcheol-Shin**
#### Summary 

This file is a template file for integrating with the Pilot Things system.

#### Changes
- Initial version
- The data received from TTI has been implemented and tested

#### Checklist
- [V] Scope: The referenced issue is addressed, there are no unrelated changes.
- [V] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [V] Testing: The changes are tested.
- [V] Documentation: Relevant documentation is added or updated.

### CODE REVIEW

**Comment by Youngcheol-Shin** [comment]
The CL:A document was signed but this pull request is still pending. Could you check it?

**Review by nejraselimovic — APPROVED** [review]
Looks good to me, did you document this integration by any chance?

**Comment by nejraselimovic** [comment]
Looks good to me, not sure why the CLA is still pending though, maybe @adriansmares knows? Also, did you document this integration by any chance?

**Comment by adriansmares** [comment]
I believe the issue is that the commits are created by https://github.com/syc0701 while the PR is created by https://github.com/Youngcheol-Shin - could you please try to sign the CLA from both accounts ?

**Pull request merged**
