### PR TITLE
Adds template for AllThingsTalk webhook

### PR DESCRIPTION
**Pull request by archix**
#### Summary

Adds template for AllThingsTalk webhook.

#### Changes

- Template for AllThingsTalk webhook is added

#### Notes

Ran the ThingsStack locally but for some reason it didn't work with specified template directory so that's why I didn't check `Testing` part in the checklist.

How I know it didn't work with my directory? It didn't show my webhook in template list and it didn't remove templates I've removed (during the test) from the shown list. 

#### Checklist

- [x ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x ] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [x ] Testing: The changes are tested.
- [x ] Documentation: Relevant documentation is added or updated.

### CODE REVIEW

**Comment by nejraselimovic** [comment]
@archix where does one find the `Network token`? I found device and ground tokens only. 

When it comes to testing webhook templates locally, the procedure is described [here](https://www.thethingsindustries.com/docs/integrations/webhooks/webhook-templates/adding_webhook_templates/). You have to specify the path to the folder containing .yml files for webhook templates in your stack configuration file (`ttn-lw-stack.yml`).

Let's first verify that the integration works properly, then I'll approve the PR

**Comment by archix** [comment]
> @archix where does one find the `Network token` on ATT Maker? I found device and ground tokens only.
> 
> When it comes to testing webhook templates locally, the procedure is described [here](https://www.thethingsindustries.com/docs/integrations/webhooks/webhook-templates/adding_webhook_templates/). You have to specify the path to the folder containing .yml files for webhook templates in your stack configuration file (`ttn-lw-stack.yml`).
> 
> Let's first verify that the integration works properly, then I'll approve the PR

Hey @nejraselimovic , `Network token` will be introduced in the UI from the next release (planned for the Monday, July 19th). Maybe I can provide a screenshot from the development instance (or maybe you can access our development if needed)?

Regarding the configuration, let me paste the `as` part from my config which doesn't work:

```
as:
  mqtt:
    public-address: '192.168.1.5:1883'
    public-tls-address: '192.168.1.5:8883'
  webhooks:
    downlink:
      public-address: '192.168.1.5:1885/api/v3'
    templates:
      directory: "/Users/igordakic/work/allthingstalk/integrations/lorawan-webhook-templates"
```

and the contents of the given directory:

```
➜  lorawan-server la -la /Users/igordakic/work/allthingstalk/integrations/lorawan-webhook-templates
total 184
drwxr-xr-x  26 igordakic  staff   832B Jul 12 19:19 .
drwxr-xr-x   6 igordakic  staff   192B Jul 12 18:07 ..
-rw-r--r--   1 igordakic  staff   210B Jul 12 11:07 .editorconfig
drwxr-xr-x  13 igordakic  staff   416B Jul 12 19:19 .git
drwxr-xr-x   6 igordakic  staff   192B Jul 12 11:07 .github
-rw-r--r--   1 igordakic  staff     2B Jul 12 11:07 CODEOWNERS
-rw-r--r--   1 igordakic  staff    11K Jul 12 11:07 LICENSE
-rw-r--r--   1 igordakic  staff   1.4K Jul 12 11:07 README.md
-rw-r--r--   1 igordakic  staff   672B Jul 12 11:07 akenza.yml
-rw-r--r--   1 igordakic  staff   665B Jul 12 15:29 attmaker.yml
-rw-r--r--   1 igordakic  staff   600B Jul 12 11:07 cayenne.yml
-rw-r--r--   1 igordakic  staff   830B Jul 12 11:07 cloudstudio.yml
-rw-r--r--   1 igordakic  staff   557B Jul 12 11:07 datacake.yml
-rw-r--r--   1 igordakic  staff   569B Jul 12 11:07 dezem.yml
-rw-r--r--   1 igordakic  staff   679B Jul 12 11:07 example.yml
-rw-r--r--   1 igordakic  staff   742B Jul 12 11:07 homey.yml
-rw-r--r--   1 igordakic  staff   622B Jul 12 11:07 iotinabox.yml
-rw-r--r--   1 igordakic  staff   647B Jul 12 11:07 qubitro.yml
drwxr-xr-x   7 igordakic  staff   224B Jul 12 11:07 schema
-rw-r--r--   1 igordakic  staff   546B Jul 12 11:07 tagoio.yml
-rw-r--r--   1 igordakic  staff   164B Jul 12 19:19 templates.yml
-rw-r--r--   1 igordakic  staff   766B Jul 12 11:07 thethingsio.yml
-rw-r--r--   1 igordakic  staff   683B Jul 12 11:07 thingspeak.yml
-rw-r--r--   1 igordakic  staff   908B Jul 12 11:07 ttnmapper.yml
-rw-r--r--   1 igordakic  staff   848B Jul 12 11:07 ubidots-plugin.yml
-rw-r--r--   1 igordakic  staff   1.2K Jul 12 11:07 uib.yml
```

Let me know if you notice something irregular and I'll try it again in the meantime.

**Comment by nejraselimovic** [comment]
Ah, I see, I thought that this is already a part of your UI. I wanted to test the integration by myself because I'm currently running this template on my local machine just fine. 

Weird, I don't see anything wrong with your setup, are you sure your configuration file is being read? Can you please try creating a `.ttn-lw-stack.yml` file in the top folder of your `lorawan-stack` fork (the same location where `CONTRIBUTING.md`, DEVELOPMENT.md` files are) and pasting the following content in there:

```
as:
  webhooks:
    templates:
      directory: "/Users/igordakic/work/allthingstalk/integrations/lorawan-webhook-templates"
```

Then try re-running the stack (without specifying the configuration file) and let me know if this works.

**Comment by archix** [comment]
Looks like you're right. It might not read my config file. I was trying to run it using `docker-compose` and `config` (open source) examples from [instructions](https://www.thethingsindustries.com/docs/getting-started/installation/configuration/#configuration-files) because I thought it's faster than configuring whole environment.

I tried with video tutorial and followed [these steps](https://www.youtube.com/watch?v=XgPSU4UkDuE) but without any luck.

Let me try and configure development env in that case and try it like that.

**Comment by adriansmares** [comment]
I'd recommend that you mount the local folder (`/Users/igordakic/work/allthingstalk/integrations/lorawan-webhook-templates`) in the container to a path like `/lorawan-webhook-templates` and use that path in the configuration. Since the stack runs in the container, it needs the folder to be available in the container.

**Comment by archix** [comment]
Thanks guys, mounting directory to container was the missing part (it should've been obvious but many thanks for it).

Other than that, I've tested the integration on our development environment and found small problem which I fixed in the latest commit. 

Since it's tested now, I'm gonna edit description and check that requirement as well.

**Review by nejraselimovic — APPROVED** [review]

**Pull request merged**
