### PR TITLE
feature/addWidgelixWebhookTemplate

### PR DESCRIPTION
**Pull request by Lockdog88**
#### Summary
Add Widglex integration to TTN

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [x] Testing: The changes are tested.
- [ ] Documentation: Relevant documentation is added or updated.

### CODE REVIEW

**Comment by Lockdog88** [comment]
@nejraselimovic Hi, I hope the PR is okay, please let me know if I missed anything. Also we may provide an account to test the hook. Thanks in advance

**Review by nejraselimovic — APPROVED** [review]
@Lockdog88 looks good to me. We should also document this, do you happen to already have some content to send me or to submit a PR in our [docs repo](https://github.com/TheThingsIndustries/lorawan-stack-docs)? If you provide me the account to your platform, I can also take care of the docs part.

**Comment by Lockdog88** [comment]
> @Lockdog88 looks good to me. We should also document this, do you happen to already have some content to send me or to submit a PR in our [docs repo](https://github.com/TheThingsIndustries/lorawan-stack-docs)? If you provide me the account to your platform, I can also take care of the docs part.

Great. I could deal with the docs by my own and prepare a PR in the docs repo, except the last part where a screenshot with widgelix template is present on the TTN :)

**Comment by Lockdog88** [comment]
@nejraselimovic when the update on ttn is possible to see? :) Thanks in advance.

**Comment by nejraselimovic** [comment]
> > @Lockdog88 looks good to me. We should also document this, do you happen to already have some content to send me or to submit a PR in our [docs repo](https://github.com/TheThingsIndustries/lorawan-stack-docs)? If you provide me the account to your platform, I can also take care of the docs part.
> 
> @nejraselimovic Great. I could deal with the docs by my own and prepare a PR in the docs repo, except the last part where a screenshot with widgelix template is present on the TTN :)

Awesome, that would be great. We'll merge the template and it will be available with the next TTS release (in 2 weeks approx.). 

We can test if everything works (before the above mentioned release) by deploying TTS locally and configuring it with a local clone of the Webhook templates repo containing your template. This process is explained [here](https://www.thethingsindustries.com/docs/integrations/webhooks/webhook-templates/adding_webhook_templates/). You can try doing it on your own, or I can do it for you, as you wish. If you do this, you can also take the screenshot of the deployed template for the documentation :)

**Comment by Lockdog88** [comment]
> Awesome, that would be great. We'll merge the template and it will be available with the next TTS release (in 2 weeks approx.).
> 
> We can test if everything works (before the above mentioned release) by deploying TTS locally and configuring it with a local clone of the Webhook templates repo containing your template. This process is explained [here](https://www.thethingsindustries.com/docs/integrations/webhooks/webhook-templates/adding_webhook_templates/). You can try doing it on your own, or I can do it for you, as you wish. If you do this, you can also take the screenshot of the deployed template for the documentation :)

@nejraselimovic If you don't mind I would like to borrow a bit of your time and ask to perform TTS template test on your side. I will prepare Widgelix account (I need "device-id" and payload format) and provide a webhook path and a token.
My email: azimin@greenmesh.org, if required.

Thanks in advance

**Pull request merged**
