### PR TITLE
Blockbax webhook template

### PR DESCRIPTION
**Pull request by blockbax**
#### Summary

Webhook template related to https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/674

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [ ] Testing: The changes are tested.
- [x] Documentation: Relevant documentation is added or updated.

### CODE REVIEW

**Comment by nejraselimovic** [comment]
This looks good to me, so I'll approve and merge this for now. We can add changes discussed in the [documentation PR](https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/674) later.

**Review by nejraselimovic — APPROVED** [review]

**Comment by blockbax** [comment]
@nejraselimovic Thanks - will keep you updated! When is the template visible? When we log in to the The Things Stack Community Edition (https://eu1.cloud.thethings.network) we do not see it.

**Comment by nejraselimovic** [comment]
> @nejraselimovic Thanks - will keep you updated! When is the template visible? When we log in to the The Things Stack Community Edition (https://eu1.cloud.thethings.network) we do not see it.

Hi @blockbax, TTS v3.16.2 was released today, so you can expect your template to be visible as soon as TTS CE is updated to this version, probably next week.

**Comment by blockbax** [comment]
> Hi @blockbax, TTS v3.16.2 was released today, so you can expect your template to be visible as soon as TTS CE is updated to this version, probably next week.

Great - thanks @nejraselimovic!

**Pull request merged**
