### PR TITLE
Create delmation.yml

### PR DESCRIPTION
**Pull request by delmation**
#### Summary

I would like to add the integration with our IoT portal.

#### Changes

This is a new integration with our IoT dashboard.

#### Notes for Reviewers

With this integration, our customers can more easily send the data to our IoT portal.

#### Checklist

- [ x ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ x ] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [ x ] Testing: The changes are tested.
- [ x ] Documentation: Relevant documentation is added or updated.

### CODE REVIEW

**Review by nejraselimovic — APPROVED** [review]

**Comment by nejraselimovic** [comment]
@delmation is this template tested? Can you create some documentation for our docs page? You can file a PR here: https://github.com/TheThingsIndustries/lorawan-stack-docs, and let me know if you need help.

**Comment by delmation** [comment]
Hi Nejra,

I have tested this template on our 'the things stack enterprise' server installation.

I will also create the documentation about this integration so that it can be posted on your site.


Best regards,

Edward de Graaff




Van: Nejra Selimović ***@***.***>
Datum: zondag, 19 februari 2023 om 19:25
Aan: TheThingsNetwork/lorawan-webhook-templates ***@***.***>
CC: Edward de Graaff | Delmation Products BV ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [TheThingsNetwork/lorawan-webhook-templates] Create delmation.yml (PR #77)

@delmation<https://github.com/delmation> is this template tested? Can you create some documentation for our docs page? You can file a PR here: https://github.com/TheThingsIndustries/lorawan-stack-docs, and let me know if you need help.

**Comment by delmation** [comment]
Hi Nejra,

I have created the documentation (see attachement)

I just don't understand how I can now add it to github via a PR.

Could you give the steps how I can add/subscribe it now.


Best regards,

Edward de Graaff




Van: Nejra Selimović ***@***.***>
Datum: zondag, 19 februari 2023 om 19:25
Aan: TheThingsNetwork/lorawan-webhook-templates ***@***.***>
CC: Edward de Graaff | Delmation Products BV ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [TheThingsNetwork/lorawan-webhook-templates] Create delmation.yml (PR #77)

@delmation<https://github.com/delmation> is this template tested? Can you create some documentation for our docs page? You can file a PR here: https://github.com/TheThingsIndustries/lorawan-stack-docs, and let me know if you need help.

**Comment by nejraselimovic** [comment]
@delmation not sure why, but I can't find the attachment. Can you please send me directly via email (nejra.selimovic@thethingsindustries.com) and I will create a PR :)

**Comment by delmation** [comment]
Hi Nejra,

I emailed the files a while ago.

I hope they arrived well.

I would like to know when these will be implemented.

Best regards,

Edward de Graaff




Van: Nejra Selimović ***@***.***>
Datum: zondag, 5 maart 2023 om 12:59
Aan: TheThingsNetwork/lorawan-webhook-templates ***@***.***>
CC: Edward de Graaff | Delmation Products BV ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [TheThingsNetwork/lorawan-webhook-templates] Create delmation.yml (PR #77)

@delmation<https://github.com/delmation> not sure why, but I can't find the attachment. Can you please send me directly via email ***@***.******@***.***>) and I will create a PR :)

**Pull request merged**
