### PR TITLE
Moved to simpler config

### PR DESCRIPTION
**Pull request by blockbax**
#### Summary

This enables users to use Blockbax inbound connectors, which is our new recommended way of integrating with The Things Stack (see https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/933 for related docs / discussion).

#### Changes

- Removed Project ID
- Removed Auto create subjects option
- Introduced Endpoint field for specifying whole base-url

#### Notes for Reviewers

...

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [x] Testing: The changes are tested.
- [x] Documentation: Relevant documentation is added or updated.

### CODE REVIEW

**Comment by nejraselimovic** [comment]
I'm currently away from the office so can't test this, but I think that the "baseURL" has to be absolute, while the variable part of the URL is defined under "paths"

**Comment by blockbax** [comment]
> I'm currently away from the office so can't test this, but I think that the "baseURL" has to be absolute, while the variable part of the URL is defined under "paths"

The user gets an absolute URL when creating an [inbound connector](https://blockbax.com/docs/project-settings/#inbound-connectors) and can just copy+past it (see below), so we thought this would be most user-friendly. Should work like this I think then right?

image

**Comment by nejraselimovic** [comment]
> > I'm currently away from the office so can't test this, but I think that the "baseURL" has to be absolute, while the variable part of the URL is defined under "paths"
> 
> The user gets an absolute "endpoint" URL when creating an [inbound connector](https://blockbax.com/docs/project-settings/#inbound-connectors) and can just copy+past it (see below), so we thought this would be most user-friendly. So the user copies an absolute URL - would it work then?
> 
> image
> 
> So in other words would with `base-url: https://api.blockbax.com/v1/projects/{projectId}/measurements?inboundConnectorId={inboundConnectorId}` (this is similar to the existing situation) and `projectId` being `test1` and the `inboundConnectorId` being `test2` the base URL would result in: `https://api.blockbax.com/v1/projects/test1/measurements?inboundConnectorId=test2`
> 
> We presumed that `base-url: "{endpoint}"` and endpoint containing the whole URL `https://api.blockbax.com/v1/projects/test1/measurements?inboundConnectorId=test2` would result in similar behavior.

@adriansmares correct me if I'm wrong here. I think the baseURL can't be defined with `base-url: "{endpoint}"`, although this would probably be the most user friendly solution. The other solution `base-url: https://api.blockbax.com/v1/projects/{projectId}/measurements?inboundConnectorId={inboundConnectorId}` would be fine as long as the length of the URL is less than 65 characters I think. If it has 65 or more characters, you would have to define a part of the URL under `paths`.

**Comment by blockbax** [comment]
> > > I'm currently away from the office so can't test this, but I think that the "baseURL" has to be absolute, while the variable part of the URL is defined under "paths"
> > 
> > 
> > The user gets an absolute "endpoint" URL when creating an [inbound connector](https://blockbax.com/docs/project-settings/#inbound-connectors) and can just copy+past it (see below), so we thought this would be most user-friendly. So the user copies an absolute URL - would it work then?
> > image
> > So in other words would with `base-url: https://api.blockbax.com/v1/projects/{projectId}/measurements?inboundConnectorId={inboundConnectorId}` (this is similar to the existing situation) and `projectId` being `test1` and the `inboundConnectorId` being `test2` the base URL would result in: `https://api.blockbax.com/v1/projects/test1/measurements?inboundConnectorId=test2`
> > We presumed that `base-url: "{endpoint}"` and endpoint containing the whole URL `https://api.blockbax.com/v1/projects/test1/measurements?inboundConnectorId=test2` would result in similar behavior.
> 
> @adriansmares correct me if I'm wrong here. I think the baseURL can't be defined with `base-url: "{endpoint}"`, although this would probably be the most user friendly solution. The other solution `base-url: https://api.blockbax.com/v1/projects/{projectId}/measurements?inboundConnectorId={inboundConnectorId}` would be fine as long as the length of the URL is less than 65 characters I think. If it has 65 or more characters, you would have to define a part of the URL under `paths`.

@nejraselimovic Thanks for checking in with your colleague @adriansmares. Would really prefer the user to copy+paste the whole URL for user-friendliness, so waiting for your reply whether it is possible or not.

**Comment by adriansmares** [comment]
The path variables are based on [RFC 6570](https://www.rfc-editor.org/rfc/rfc6570.txt) - they are not just textual replacements of of the values. It is indeed the case that it is not possible to provide the full URL as a single variable.

**Comment by blockbax** [comment]
> The path variables are based on [RFC 6570](https://www.rfc-editor.org/rfc/rfc6570.txt) - they are not just textual replacements of of the values. It is indeed the case that it is not possible to provide the full URL as a single variable.
> 
> You may consider having a singular identifier for your entry point that is large (contains both `projectId` and `inboundConnectorId`) and do the re-routing internally, if having a single variable to copy paste is paramount.

@adriansmares A didn't realize that. I did some digging to the specs and I derived that `{+endpoint}` will do the job. I even found a testing tool online [here](https://bigbluehat.github.io/vue-uri/) which confirmed my idea (see below) for screenshot. What you do think?

image

Indeed if I were to use it without the `+` it would not work (see below).

image

**Comment by nejraselimovic** [comment]
> > The path variables are based on [RFC 6570](https://www.rfc-editor.org/rfc/rfc6570.txt) - they are not just textual replacements of of the values. It is indeed the case that it is not possible to provide the full URL as a single variable.
> > You may consider having a singular identifier for your entry point that is large (contains both `projectId` and `inboundConnectorId`) and do the re-routing internally, if having a single variable to copy paste is paramount.
> 
> @adriansmares A didn't realize that. I did some digging to the specs and I derived that `{+endpoint}` will do the job.
> 
> See:
> 
> > add the plus ("+") operator, for expansion of
> > values that are allowed to include reserved URI characters
> 
> In the [RFC 6570](https://www.rfc-editor.org/rfc/rfc6570.txt) specs.
> 
> I also found a testing tool online [here](https://bigbluehat.github.io/vue-uri/) which confirmed my idea (see below) for screenshot. What you do think?
> 
> image
> 
> Indeed if I were to use it without the `+` it would not work (see below).
> 
> image

@blockbax I'll check this and get back to you with an update soon

**Comment by nejraselimovic** [comment]
@blockbax @adriansmares so I checked the `base-url: "{+endpoint}"` workaround and it doesn't seem to work, I get the `invalid base_url: value must be absolute` error in the Console.

**Comment by blockbax** [comment]
@nejraselimovic @adriansmares Sorry for the late reply, was off the reader due to vacation. 

A pity it doesn't work out of the box. You guys got any idea why? 

As shared earlier that according to [RFC 6570](https://www.rfc-editor.org/rfc/rfc6570.txt) it should work like this. Also [URI.js](https://bigbluehat.github.io/vue-uri/) seems to implement it like this. Would be valuable if you guys can give any insight on how it is implemented on your end to know why it doesn't work as expected?

**Comment by adriansmares** [comment]
I've actually just re-tested this and it works.

https://user-images.githubusercontent.com/36161392/189644273-6d38f7ac-f3ef-472a-bb61-4e05beea6505.mov

I think this is good to - can you confirm @nejraselimovic ?

**Comment by nejraselimovic** [comment]
> I've actually just re-tested this and it works.
> 
>  Screen.Recording.2022-09-12.at.14.38.09.mov 
> I think this is good to - can you confirm @nejraselimovic ?

Hmm, this is weird. Wondering why I got the error.. maybe browser caching :/ anyway, yeah, this looks good to go!

**Review by nejraselimovic — APPROVED** [review]

**Pull request merged**
