### PR TITLE
Adding a new template for Homey

### PR DESCRIPTION
**Pull request by OOHehir**
#### Summary
New template for a 'Homey' home automation device 

#### Changes
New template

#### Notes for Reviewers
Homey manufacturers guidelines from:
https://apps.developer.homey.app/cloud/webhooks

#### Checklist

- [*] Scope: The referenced issue is addressed, there are no unrelated changes.
- [*] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [*] Testing: The changes are tested.
- [*] Documentation: Relevant documentation is added or updated.

### CODE REVIEW

**Comment by OOHehir** [comment]
Additionally the 'Homey' logos are [here](https://drive.google.com/drive/mobile/folders/1fjVrFT2WGf-BRAwzAOOdoVQPpE79HqeU) but I've no method of hosting them.

**Review by nejraselimovic — APPROVED** [review]

**Comment by nejraselimovic** [comment]
@OOHehir please add the template in `templates.yml` otherwise the template won't be shown

**Comment by nejraselimovic** [comment]
@OOHehir any chance you can provide us some documentation on how to integrate Homey and TTS? We tend to have the documentation for all cloud platforms we integrate with: https://www.thethingsindustries.com/docs/integrations/cloud-integrations/. You could file a PR in our documentation repo: https://github.com/TheThingsIndustries/lorawan-stack-docs, or you could send me some content and I could turn it into a PR.

**Comment by OOHehir** [comment]
@nejraselimovic for my Homey app the instructions are [here](https://github.com/OOHehir/connector.ttn/blob/main/README.md#setup-using-webhook-template---preferred-method). 

However if other developers use the template for other apps their implementation may differ slightly but I imagine it'll be relatively similar.

**Comment by nejraselimovic** [comment]
> @nejraselimovic for my Homey app the instructions are [here](https://github.com/OOHehir/connector.ttn/blob/main/README.md#setup-using-webhook-template---preferred-method).
> 
> However if other developers use the template for other apps their implementation may differ slightly but I imagine it'll be relatively similar.

Awesome, thank you!

**Pull request merged**
